#!/bin/bash
# Check the current owner of the file hello
owner=$(stat -c %U hello)

# If the current owner is guillaume, change the owner to betty
if [ "$owner" = "guillaume" ]; then
    sudo chown betty hello
fi
